package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"testing"

	"golang.org/x/tools/go/packages"
)

func TestReadFuncsPreservesHandwrittenHashes(t *testing.T) {
	files := []string{
		`package block
  func (Vanilla) EncodeBlock() {}
  func (Network) EncodeBlock() {}
  func (Network) Hash() {}
  func (Pointer) EncodeBlock() {}
  func (*Pointer) Hash() {}`,
		`// Code generated by cmd/blockhash; DO NOT EDIT.
  package block
  func (Vanilla) Hash() {}`,
	}
	pkg := &packages.Package{}
	for _, source := range files {
		file, err := parser.ParseFile(token.NewFileSet(), "", source, parser.ParseComments)
		if err != nil {
			t.Fatal(err)
		}
		pkg.Syntax = append(pkg.Syntax, file)
	}
	b := &hashBuilder{funcs: map[string]*ast.FuncDecl{}}
	b.readFuncs(pkg)
	if len(b.funcs) != 1 || b.funcs["Vanilla"] == nil {
		t.Fatalf("selected encoders: %v", b.funcs)
	}
}
